brooder/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask, session, g, render_template
import sys
sys.path.append('/home/pi')

app = Flask(__name__)
app.config.from_object('siteconfig')
app.secret_key = ']\xf8\xaf\xc4f\x101a\xe2<\x96\x84\xcd\xf1\x01T\xe9\xda\x97s\xc5,\x06&'

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from brooder.views import brooder
app.register_blueprint(brooder.mod)

brooder/views/brooder.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, session, redirect, url_for, \
    request, flash, g, jsonify, abort
from Brooder.brooder import Brooder
from Brooder.config import Config
from Brooder.temp import Sensor
from datetime import datetime, timedelta

mod = Blueprint('brooder', __name__)

@mod.route('/')
def index():
  """
    Get the list of active sensors
  """
  sensor_list = Brooder().listAll()
  config = Config()
  config._sensor = Sensor(id=config.reference)
  title = str(round(config._sensor.value, 1)) + 'C Brooder Control'
  for sensor in sensor_list:
    sensor.current_value = round(sensor._sensor.value, 1)
    if sensor.set_temperature:
      sensor.max_value = round(sensor.set_temperature, 1)
    else:
      if sensor.cycle_enabled:
        sensor.max_value = round(config.rampedTemp(sensor.cycle_started),1)
      else:
        sensor.max_value = round(config.temp_high, 1)

  return render_template('brooder/index.html', sensor_list = sensor_list, config = config, title=title)

@mod.route('/config/', methods=['GET', 'POST'])
def config():
  """
    Set up configuration
  """
  config = Config()
  changed = False
  if request.method == "POST":
    for key in request.form:
      if config.setValueFromForm(key, request.form[key]):
        changed = True
    if changed:
      flash('Config saved')
      config.save()

  return render_template('brooder/config.html', config=config, title='Brooder Config')

@mod.route('/node/<nid>/', methods=['GET', 'POST'])
def node(nid):
  """
    Get or set stats on a single sensor
  """
  node = Brooder()
  nodelist = node.listAll()
  node.load(int(nid)) # This avoids calling the pin init.
  node._sensor = Sensor(id=node.sensor)
  config = Config()

  set_node_defaults(node, config)
  node.current_value = round(node._sensor.value,1)
  cycle_day = datetime.now() - node.cycle_started
  node.cycle_day = cycle_day.days

  if node.set_temperature:
    node.max_value = round(node.set_temperature,1)
  elif node.cycle_enabled:
    node.max_value = round(config.rampedTemp(node.cycle_started),1)
  else:
    node.max_value = round(config.temp_high, 1)

  title = str(node.current_value) + 'C ' + node.name

  nodes = []
  for n in nodelist:
    if n.id != node.id:
      nodes.append({'id': n.id, 'name': n.name})
  if request.method == "POST":
    # Find what we've been given and update the config
    if ('power' in request.form and request.form['power']):
      node.setEnabled(request.form['power'] == 'on')
    if ('cycle' in request.form and request.form['cycle']):
      node.setCycle(request.form['cycle'] == 'on')
    elif ('cycleday' in request.form ):
      node.setCycleDay(int(request.form['day']))
    elif ('clone' in request.form and request.form['clone']):
      clonefrom = Brooder()
      clonefrom.load(int(request.form['clonefrom']))
      node.clone(clonefrom)
    elif ( 'set' in request.form ):
      node.setTemperature(request.form['temp'])
    elif ( 'default' in request.form and request.form['default'] == '1' ):
      node.setDefault()
    elif ('refresh' in request.form):
      pass
    node.load(node.id)
    set_node_defaults(node, config)

  return render_template('brooder/node.html', node = node, config=config, nodelist = nodes, title=title)


def set_node_defaults(node, config):

  node.current_value = round(node._sensor.value,1)
  cycle_day = datetime.now() - node.cycle_started
  node.cycle_day = cycle_day.days

  if node.set_temperature:
    node.max_value = round(node.set_temperature,1)
  elif node.cycle_enabled:
    node.max_value = round(config.rampedTemp(node.cycle_started),1)
  else:
    node.max_value = round(config.temp_high, 1)

brooder/templates/brooder/config.html
{% extends "layout.html" %}
{% block body %}
<div class="fullwidth">
<h2>Brooder Configuration</h2>
<form id="conffrm" method="POST">
<div class="config col-xs-12 col-sm-3">
<div class="entity clearfix"><label for="temp_high">Max Temperature</label><input type="text" name="temp_high" value="{{ config.temp_high }}"/></div>
<div class="entity clearfix"><label for="temp_low">Min Temperature</label><input type="text" name="temp_low" value="{{ config.temp_low }}"/></div>
<div class="entity clearfix"><label for="hysterisis">Hysterisis</label><input type="text" name="hysterisis" value="{{ config.hysterisis }}"/></div>
<div class="entity clearfix"><label for="reference">Sensor ID</label><input type="text" name="reference" value="{{ config.reference }}"/></div>
<div class="entity clearfix"><label for="time_start">Light On Time</label><input type="text" name="time_start" value="{{ config.time_start }}"/></div>
<div class="entity clearfix"><label for="time_end">Light Off Time</label><input type="text" name="time_end" value="{{ config.time_end }}"/></div>
<div class="entity clearfix"><label for="cycle_offset">Delay to start of cycle</label><input type="text" name="cycle_offset" value="{{ config.cycle_offset }}"/></div>
<div class="entity clearfix"><label for="ramp_factor">Degrees per day of cycle</label><input type="text" name="ramp_factor" value="{{ config.ramp_factor }}"/></div>
<div class="actions btn"><input type="submit" name="submit" value="Submit"/></div>
</div>
</form>
</div>
{% endblock %}

brooder/templates/brooder/index.html
{% extends "layout.html" %}
{% block head %}
<meta http-equiv="refresh" content="20" />
{% endblock %}
{% block body %}
<div class="col-xs-12">
<p><strong>Current Temp: {{ "%.1f"|format(config._sensor.value) }}</strong></p>
<p><strong>Light Starts: {{ config.time_start }} Ends: {{ config.time_end }}</strong></p>
</div>
<div class="container-fluid">
{% for data in sensor_list %}
<div class="col-sm-3 col-xs-12">
<a href="{{ url_for('brooder.node', nid=data.id) }}">
<div class="node{{ " old" if data._sensor.age() > 3600 }}{{ " disabled" if not data.enabled }}">
<div class="title">{{ data.name }}</div>
<div class="data">
<span class="current">{{ data.current_value}}</span>
<span class="max">{{ data.max_value }}</span>
<div class="indicators">
<span class="light {{ "on" if data.light_state else "off" }}"><i class="fa fa-fw fa-lightbulb-o"></i></span>
<span class="heat {{ "on" if data.heater_state else "off" }}"><i class="fa fa-fw fa-fire"></i></span>
</div>
</div>
</div>
</div>
</a>
{% endfor %}
</div>
{% endblock %}

brooder/templates/brooder/node.html
{% extends "layout.html" %}
{% block head %}
<!-- <meta http-equiv="refresh" content="20"/> -->
{% endblock %}
{% block body %}
<h1>{{ node.name }}</h1>
<div class="col-sm-3">
<div>Last Updated {{ "%d"|format(node._sensor.age()) }} seconds ago</div>
<div class="node{{ " old" if node._sensor.age() > 3600 }}{{ " disabled" if not node.enabled }}">
 <div class="data">
  <span class="current">{{ node.current_value }}</span>
  <span class="max">{{ node.max_value }}</span>
  <div class="indicators">
   <span class="light {{ "on" if node.light_state else "off" }}"><i class="fa fa-fw fa-lightbulb-o"></i></span>
   <span class="heat {{ "on" if node.heater_state else "off" }}"><i class="fa fa-fw fa-fire"></i></span>
  </div>
 </div>
</div>
<form method="post" id="tempset">
  <input type="hidden" id="power" name="power" value="" />
  <input type="hidden" id="cycle" name="cycle" value="" />
  <div class="row">
  <div class="button col-xs-6">Power <a href="#" class="toggler{{ " on" if node.enabled else " off" }}" data-target="power" data-state="{{ "off" if node.enabled else "on" }}"><i class="fa fa-fw fa-toggle-{{ "on" if node.enabled else "off" }}"></i></a></div>
  <div class="button col-xs-6">Cycle <a href="#" class="toggler{{ " on" if node.cycle_enabled else " off" }}" data-target="cycle" data-state="{{ "off" if node.cycle_enabled else "on" }}"><i class="fa fa-fw fa-toggle-{{ "on" if node.cycle_enabled else "off" }}"></i></a></div>
  </div>
  <div class="row">
   <div id="temperature"></div>
  </div>
  <div class="row">
   <div class="col-xs-6"><input type="text" size="5" id="temp-txt" name="temp" value="{{ node.max_value }}" /></div>
   <div class="col-xs-6"><button type="submit" class="btn" name="set" value="1">Set Temp</button></div>
  </div>
  <div class="row">
    <div id="cycleday"></div>
  </div>
  <div class="row">
   <div class="col-xs-6"><input type="text" size="5" id="day" name="day" value="{{ node.cycle_day }}" /></div>
   <div class="col-xs-6"><button type="submit" class="btn" name="cycleday" value="1">Set Cycle Day</button></div>
  </div>
  <div class="row">
    <div class="col-xs-6"><select name="clonefrom">
    {% for o in nodelist %}
    <option value="{{ o.id }}">{{ o.name }}</option>
    {% endfor %}
    </select></div>
    <div class="col-xs-6"><button type="submit" class="btn" name="clone" value="1">Clone</button></div>
  </div>
  <div class="row">
    <div class="col-xs-6"><button type="submit" class="btn" name="default" value="1">Default</button></div>
    <div class="col-xs-6"><button type="submit" class="btn" name="refresh" value="1">Refresh</button></div>
  </div>
</form>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.toggler').click(function() {
  var name = $(this).data('target');
  $('#' + name).val($(this).data('state'));
  $('#tempset').submit();
});
$('#temperature').slider({
  min: {{ config.temp_low }},
  max: {{ config.temp_high }},
  value: {{ node.set_temperature if node.set_temperature else config.temp_high }},
  change: function(event, ui) {
    $('#temp-txt').val(ui.value);
  },
});
$('#temp-txt').change( function() {
  $('#temperature').slider("value", $(this).val());
});
$('#cycleday').slider({
  min: 0,
  max: 35,
  value: {{ node.cycle_day }},
  change: function(event, ui) {
    $('#day').val(ui.value);
  }
});
$('#day').change( function() {
  $('#cycleday').slider("value", $(this).val());
});
</script>
{% endblock %}

brooder/templates/layout.html
<!doctype html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />
{%block head %}{% endblock %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"></link>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}"></link>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/jquery-ui.min.css') }}">
<title>{{ title }}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#thenav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('brooder.index') }}">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="thenav">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('brooder.config') }}">Config</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
<div class="center-block">
{%block body %}{% endblock %}
</div>
</div>
<script src="{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{%block js %}{% endblock %}
</body>
</html>